const fortunes = [

"You survived 100% of your hardest days so far.",
"Rest is not quitting. It is healing.",
"You are allowed to begin again today.",
"Someone you haven’t met yet will be glad you stayed.",
"This moment is temporary — your story is not finished.",
"You matter even when your mind says otherwise.",
"Small steps still move you forward.",
"You are not behind in life. You are on your path.",
"Your presence makes the world different.",
"Hope sometimes whispers instead of shouting.",
"The future has moments you haven't smiled at yet.",
"You deserve gentleness — especially from yourself.",
"Even slow healing is healing.",
"Today only asks you to stay.",
"The light returns slowly, but it returns.",
"If today felt heavy, it doesn’t mean tomorrow will feel the same.",
"You don’t have to solve your whole life tonight — just breathe for now.",
"Some days surviving quietly is already an achievement.",
"It’s okay if you’re tired of being strong. Rest counts too.",
"You are not failing — you are learning how to carry yourself forward.",
"The version of you that kept going deserves kindness.",
"You are allowed to take life one small moment at a time.",
"Even when you feel invisible, your existence still matters deeply.",
"You don’t need to have everything figured out to keep going.",
"There are peaceful days ahead that you cannot see yet.",
"It’s okay to pause. Growth still happens slowly.",
"You are doing better than your thoughts give you credit for.",
"Your story still has chapters waiting to surprise you.",
"You are not alone in feeling this way — many hearts understand.",
"Today may be hard, but you are harder to break.",
"The world is quieter without your smile — it needs you here.",
"Your effort to keep going matters more than perfection.",
"Not every day needs progress; some days only need patience.",
"You deserve moments of calm after everything you’ve carried.",
"The fact that you’re here right now means hope is still working inside you."

];